name: new_flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  googleapis: ^14.0.0
  googleapis_auth: ^1.4.0
  google_sign_in: ^6.1.5
  path_provider: ^2.1.2
  archive: ^4.0.5
  uuid: ^4.2.1
  permission_handler: ^11.0.1
  photo_manager: ^3.6.4
  http: ^1.3.0
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  flutter_background: ^1.3.0
  lifecycle: ^0.9.0 # バージョンを最新化

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/credentials.json
